title: "Mani Majd's Portfolio"
description: "Engineering Science Student at U of T | Passionate About Data Science and Machine Learning"
author: Mani Majd
theme: jekyll-theme-minimal
url: "https://ManiMajd89.github.io"
baseurl: "" # Leave empty unless you're using a subfolder.
github_username: ManiMajd89

# Social Links
social_links:
  - name: GitHub
    url: https://github.com/ManiMajd89
  - name: Devpost
    url: https://devpost.com/manimajd1389
  - name: Email
    url: mailto:mani.majd@mail.utoronto.ca
