title: Mani Majd's Portfolio
description: A showcase of my journey, projects, and contact information.
theme: jekyll-theme-minimal
author: Mani Majd
email: manimajd@example.com
url: https://manimajd89.github.io
github_username: ManiMajd89

# Navigation links
navigation:
  - title: "Home"
    url: /
  - title: "Portfolio"
    url: /portfolio/
  - title: "Projects"
    url: /projects/
  - title: "Contact Me"
    url: /contact/
