# Site Settings
title: Mani Majd's Portfolio
description: Third-year U of T Engineering Science student specializing in Robotics with an AI minor.
theme: jekyll-theme-minimal
author: Mani Majd
email: mani.majd@mail.utoronto.ca
url: https://ManiMajd89.github.io
github_username: ManiMajd89

# Navigation Menu
navigation:
  - title: "Home"
    url: /
  - title: "Portfolio"
    url: /portfolio/
  - title: "Projects"
    url: /projects/
  - title: "Contact Me"
    url: /contact/

# Enable Plugins (Optional)
plugins:
  - jekyll-seo-tag # Improves SEO
  - jekyll-sitemap # Generates a sitemap.xml for search engines

# Markdown Configuration
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub Flavored Markdown
